# Generated by Django 5.2.3 on 2025-06-17 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clear', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CallbackRequest',
            new_name='Callback',
        ),
    ]
