# Generated by Django 5.2.3 on 2025-06-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clear', '0002_rename_callbackrequest_callback'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
